Fix inconsistency of `size_t` => `int` for mp3dec_iterate_w
This PR fixes an inconsistency of `size_t` => `int` for mp3dec_iterate_w.
On Windows size_t and int may not match so the following might arise depending
on Configuration:
```
error C2556: 'size_t mp3dec_iterate_w(const wchar_t *,MP3D_ITERATE_CB,void *)': overloaded function differs only by return type from 'int mp3dec_iterate_w(const wchar_t *,MP3D_ITERATE_CB,void *)'
```

This fix fixes the issue

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>